name: 'Build a test package'
on:
  pull_request:
  push:
    branches: [ main, stable, testing ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v3.5.2
      - name: 'Build package'
        id: build
        uses: jtdor/build-deb-action@v1.7.0
        with:
          buildpackage-opts: -us -uc
          docker-image: debian:bullseye-slim
      - name: 'Upload artifacts'
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: package
          path: debian/artifacts
